# Generated by Django 4.2.1 on 2023-11-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_customuser_address_customuser_city_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approvel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_certificate/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_idproof/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
