# Generated by Django 4.2.1 on 2023-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_approvel_customuser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teacher_request',
            field=models.BooleanField(default=False),
        ),
    ]
