# Generated by Django 4.2.1 on 2023-11-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_alter_customuser_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
