# Generated by Django 4.2.1 on 2023-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_customuser_ifsc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_certificate/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_idproof/'),
        ),
    ]
