# Generated by Django 4.2.1 on 2023-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_subscripe',
            field=models.BooleanField(default=False),
        ),
    ]
