# Generated by Django 4.2.1 on 2023-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_subscripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
